plugin: aws_ec2

aws_access_key: "AKIATP6LCA6BRKOCZN6Y"
aws_secret_key: "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"

regions:
  - ap-southeast-2

filters:
  instance-state-name : running
 
keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
